
version: '3'
services:
  web:
    container_name: web
    build: .
    ports:
       - "5000:5000"
    volumes:
       - .:/code
  redis:
    container_name: redis
    image: "redis:alpine"
  db:
    container_name: db
    image: postgres
    environment:  
       POSTGRES_PASSWORD: example
  adminer:
    container_name: adminer
    image: adminer  
    ports:      
       - 8080:8080
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
       - "2181:2181"
  kafka:
    container_name: kafka
    build: .
    ports:
       - "9092"
    environment:
       KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
